test.exe: test01.cpp ../clases/Esfera.h ../clases/Poligono.h ../clases/Punto.h ../clases/Shape.h ../clases/Utils.h ../clases/Cilindro.h
	g++ test01.cpp ../clases/Esfera.h ../clases/Poligono.h ../clases/Punto.h ../clases/Shape.h ../clases/Utils.h ../clases/Cilindro.h -o test01.exe
